// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_0uuXa4_kSg4EA4VIU3YUBmSuiW9kY0o',
    appId: '1:679974678671:web:453cca3210051d00bbc0fa',
    messagingSenderId: '679974678671',
    projectId: 'taskmanager-ef980',
    authDomain: 'taskmanager-ef980.firebaseapp.com',
    storageBucket: 'taskmanager-ef980.appspot.com',
    measurementId: 'G-E2LJV1L5MX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbuSOLEcmKmwb12J1EZKnH4--VlxMGVho',
    appId: '1:679974678671:android:cdeea850da3a741cbbc0fa',
    messagingSenderId: '679974678671',
    projectId: 'taskmanager-ef980',
    storageBucket: 'taskmanager-ef980.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq0wLVNcJFR68n10VsYAJxTrb6ciy_3HA',
    appId: '1:679974678671:ios:b5862359b759fcacbbc0fa',
    messagingSenderId: '679974678671',
    projectId: 'taskmanager-ef980',
    storageBucket: 'taskmanager-ef980.appspot.com',
    iosClientId: '679974678671-bp8bvmf694o6a85192knrifiehjsokve.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq0wLVNcJFR68n10VsYAJxTrb6ciy_3HA',
    appId: '1:679974678671:ios:b5862359b759fcacbbc0fa',
    messagingSenderId: '679974678671',
    projectId: 'taskmanager-ef980',
    storageBucket: 'taskmanager-ef980.appspot.com',
    iosClientId: '679974678671-bp8bvmf694o6a85192knrifiehjsokve.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_0uuXa4_kSg4EA4VIU3YUBmSuiW9kY0o',
    appId: '1:679974678671:web:46cb40121195abf8bbc0fa',
    messagingSenderId: '679974678671',
    projectId: 'taskmanager-ef980',
    authDomain: 'taskmanager-ef980.firebaseapp.com',
    storageBucket: 'taskmanager-ef980.appspot.com',
    measurementId: 'G-HC5WDMWFYT',
  );

}